<?xml version="1.0" encoding="utf-8"?><Database Name="pnevmotools" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TIGRIFERUM-PC\SQLEXPRESS;Initial Catalog=pnevmotools;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pnevmotoolsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pics" Member="Pics">
    <Type Name="Pic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="path" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="Item_Pic" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rezba" Member="Rezbas">
    <Type Name="Rezba">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Rezba_Item" Member="Items" ThisKey="ID" OtherKey="Rezba" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Sizes" Member="Sizes">
    <Type Name="Size">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Size_Item" Member="Items" ThisKey="ID" OtherKey="Size" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="FreeDelivery" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Category" Member="Categories" ThisKey="ID" OtherKey="ParentCategory" Type="Category" />
      <Association Name="Category_Item" Member="Items" ThisKey="ID" OtherKey="Category" Type="Item" />
      <Association Name="Category_Category" Member="Category1" ThisKey="ParentCategory" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IncomeOrder" Member="IncomeOrders">
    <Type Name="IncomeOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PricePerItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemsLeft" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_IncomeOrder" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PricePerItem" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Item_OrderDetail" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" OtherKey="ID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rezba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarginType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MarginValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UseInLister" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WholeMarginValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WholeMinCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Item_Pic" Member="Pics" ThisKey="ID" OtherKey="ItemID" Type="Pic" />
      <Association Name="Item_IncomeOrder" Member="IncomeOrders" ThisKey="ID" OtherKey="ItemID" Type="IncomeOrder" />
      <Association Name="Item_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="ItemID" Type="OrderDetail" />
      <Association Name="Category_Item" Member="Category1" ThisKey="Category" OtherKey="ID" Type="Category" IsForeignKey="true" />
      <Association Name="Rezba_Item" Member="Rezba1" ThisKey="Rezba" OtherKey="ID" Type="Rezba" IsForeignKey="true" />
      <Association Name="Size_Item" Member="Size1" ThisKey="Size" OtherKey="ID" Type="Size" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Pnone2" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Appartmant" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryCost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="OrderID" Type="OrderDetail" />
    </Type>
  </Table>
</Database>